version: "3.9"
services:
  app:
    image: varlog/app:latest
    ports:
      - "8000:8000"
  registry:
    image: varlog/registry:latest
    ports:
      - "8888:8888"
  primary:
    image: varlog/server:latest
    depends_on:
      - registry
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      HOSTNAME: "primary:8080"
      REGISTRY_URL: "http://registry:8888"
    volumes:
      - ./fake_data:/var/log
  secondary:
    image: varlog/server:latest
    depends_on:
      - registry
    ports:
      - "8081:8080"
    env_file: .env
    environment:
      HOSTNAME: "secondary:8080"
      REGISTRY_URL: "http://registry:8888"
    volumes:
      - ./fake_data:/var/log
  teritary:
    image: varlog/server:latest
    depends_on:
      - registry
    ports:
      - "8082:8080"
    env_file: .env
    environment:
      HOSTNAME: "teritary:8080"
      REGISTRY_URL: "http://registry:8888"
    volumes:
      - ./fake_data:/var/log
