version: "3.9"
services:
  app:
    image: varlog/app:latest
    ports:
      - "8000:8000"
  server:
    image: varlog/server:latest
    ports:
      - "8080:8080"
    env_file: .env
  secondary:
    image: varlog/server:latest
    ports:
      - "8081:8080"
    env_file: .env
  teritary:
    image: varlog/server:latest
    ports:
      - "8082:8080"
    env_file: .env
