version: "3.9"
services:
  varlog:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
  varlog_a:
    build: .
    env_file: .env
  varlog_b:
    build: .
    env_file: .env
  varlog_c:
    build: .
    env_file: .env
